export const GET_HOME_LIST = 'home/GET_HOME_LIST';
export const LOAD_MORE_LIST = 'home/LOAD_MORE_LIST';
export const BACKTOP_SCROLL_INFO = 'home/BACKTOP_SCROLL_INFO';
export const BARCODE_SHOW_INFO = 'home/BARCODE_SHOW_INFO';
export const REFRESH_RECOMMENDAUTHOR_LIST= 'home/REFRESH_RECOMMENDAUTHOR_LIST';
export const GET_TOTAL_RECOMMENDAUTHORSLIST= 'home/GET_TOTAL_RECOMMENDAUTHORSLIST';
export const BC_ICON_TOGGLE= 'home/BC_ICON_TOGGLE';
export const GET_BANNERPIC_LIST= 'home/GET_BANNERPIC_LIST';